name: Say hello on push.

on: ["push"]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "A push was done."

      - name: Display context
        run : ${{ github }}
